services:
  - type: web
    name: rag-backend
    env: python
    plan: starter   # or higher for more resources
    buildCommand: |
      apt-get update && apt-get install -y chromium chromium-driver
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn fast:app --host 0.0.0.0 --port $PORT --workers 1
    disk:
      name: chroma-data
      mountPath: /opt/render/project/src/chroma_index
      sizeGB: 0.5  # Increase if storing more data
    envVars:
      - key: CHROME_BIN
        value: /usr/bin/chromium
      - key: CHROMEDRIVER_PATH
        value: /usr/bin/chromedriver
